---
# tasks file for basic_package
- name: Update and upgrade apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
